# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("browser.download.dir", "/mnt/sda1/downloads_linux");
user_pref("browser.download.folderList", 2);
user_pref("browser.cache.disk.parent_directory", "/mnt/sda1/downloads_linux/.cache/waterfox");

